### ISSUE TITLE
Missing ReadStream and WriteStream classes

### ISSUE THREAD

**Issue by dave-irvine** [streamich/unionfs#1]
If you try and do (admittedly weird) things with graceful-fs, it expects `fs` (which can be replaced by unionfs) to have ReadStream and WriteStream.

Can you expose those on unionfs?

https://github.com/isaacs/node-graceful-fs/blob/master/graceful-fs.js#L156

**Comment by digitalkaoz** [comment]
@streamich any chance we get this into `unionfs`?
