### ISSUE TITLE
[RFC] Downstream projects

### ISSUE THREAD

**Issue by elmpp** [streamich/unionfs#452]
Unionfs and memfs are great. Admirably, they stick to the FS api pretty closely. 

I am looking to support some more advanced use cases involving FSs that are more varied and deserve their own scope. They will lean quite heavily on both libraries and I'm hoping this ticket can lead to some suggestions about how this could be best achieved. [Prior art](https://github.com/streamich/memfs/issues/48#issuecomment-340404484)

I hope to support the following use cases:
 - a proxy wrapper for a volume to ensure directories exist before files are created
 - compare 2 volumes and create a diff
 - copy contents of one volume onto another
 - support other [FS-like volumes](https://github.com/yarnpkg/berry/tree/master/packages/yarnpkg-fslib/sources) such as ZipFS etc

It's in very early stages but [these are the exports](https://github.com/elmpp/unionfs-extra/blob/master/src/index.ts#L4) i'm hoping to see be made available to progress. If I'm missing something please do comment. 

PRs:
 - ~[method metadatas](https://github.com/streamich/unionfs/pull/441/files#diff-f41e9d04a45c83f3b6f6e630f10117feR3)~
 - [IFS](https://github.com/streamich/unionfs/pull/451)

**Comment by G-Rath** [comment]
I'm going to close this due to age and because I think it's too broad to be properly actionable - feel free to open a new issue (or several) if you have ideas you'd like to discuss :)
