### ISSUE TITLE
Upgrade fs-monkey dependency

### ISSUE THREAD

**Issue by ayvaroff** [streamich/unionfs#757]
Please upgrade [fs-monkey](https://github.com/streamich/fs-monkey) dependency to the latest one (**v1.0.3**).

I encountered an issue when `rmSync` function is not available when using [memfs](https://github.com/streamich/memfs) with [uninonfs](https://github.com/streamich/unionfs). After some investigation I found out that the version of **fs-monkey** is different and doesn't include new implemented methods.

I wanted to create PR myself but due to permissions this issue was created instead.

**Comment by G-Rath** [comment]
v1.0.4 was released a couple of days ago which has support for `rm` and `rmSync`, so this is now resolved
